
image: Visual Studio 2019

clone_depth: 3

platform:
  - x64

configuration:
  - Release
  
matrix:
  fast_finish: false

init:
  - cmd: cmake --version

before_build:
  - git submodule update --init --recursive
  - mkdir build
  - cd build
  - echo Building tinyxml2
  - git clone https://github.com/leethomason/tinyxml2.git
  - cd tinyxml2 
  - mkdir build
  - cd build
  - cmake -Dtinyxml2_SHARED_LIBS:BOOL=ON -DCMAKE_INSTALL_PREFIX=../../usr ..
  - cmake --build . --config Release --target ALL_BUILD
  - cmake --install .
  - cd ../..
  - echo Building sqlite3
  - git clone https://github.com/strandfield/sqlite-amalgamation.git
  - cd sqlite-amalgamation
  - cmd: c:\"Program Files (x86)"\"Microsoft Visual Studio"\2019\Community\VC\Auxiliary\Build\vcvars64.bat
  - cmd: cl sqlite3.c -DSQLITE_API=__declspec(dllexport) -link -dll -out:sqlite3.dll
  - cd ..
  - copy sqlite-amalgamation\sqlite3.dll usr\bin
  - copy sqlite-amalgamation\sqlite3.lib usr\lib
  - copy sqlite-amalgamation\sqlite3.h usr\include
  - cmake ..

build_script:
  - cmake --build . --config Release -- %MSBUILD_ARGS%

test_script:
  - dir
  - activate.bat
  - set PATH=%cd%\Release;%PATH%
  - csnap --version
