name: CMake Build

on: [push]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Checkout submodules
      run: git submodule update --init --recursive

    - name: Build tinyxml2
      working-directory: ${{github.workspace}}
      run: |
        mkdir build
        cd build
        git clone https://github.com/leethomason/tinyxml2.git
        cd tinyxml2
        mkdir build
        cd build
        cmake -Dtinyxml2_SHARED_LIBS:BOOL=OFF ..
        cmake --build . --config Release
        cmake --install .
        
    - name: Install SQLite3
      run: apt-get install -y libsqlite3-dev

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
